-- =========================================================
-- users
-- =========================================================
CREATE TABLE users (
    user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR,
    "password" TEXT,
    email VARCHAR,
    address_main TEXT,
    address_dong TEXT,
    temperature VARCHAR DEFAULT '36.5',
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_is_deleted ON users(is_deleted);

-- =========================================================
-- items_category_enum
-- =========================================================
CREATE TABLE items_category_enum (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_text TEXT NOT NULL
);

INSERT INTO items_category_enum (category_text) VALUES
('디지털기기'),('생활가전'),('가구/인테리어'),('생활/주방'),('유아동'),
('유아도서'),('여성의류'),('여성잡화'),('남성패션/잡화'),('뷰티/미용'),
('스포츠/레저'),('취미/게임/음반'),('도서'),('티켓/교환권'),
('가공식품'),('건강기능식품'),('반려동물용품'),('식물'),
('기타 중고물품'),('삽니다');

-- =========================================================
-- status_enum
-- =========================================================
CREATE TABLE status_enum (
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_text TEXT NOT NULL
);

INSERT INTO status_enum (status_text) VALUES
('판매중'), ('예약중'), ('판매완료');

-- =========================================================
-- items
-- =========================================================
CREATE TABLE items (
    item_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    seller_id INTEGER,
    item_price VARCHAR,
    item_title TEXT,
    item_description TEXT,
    item_location TEXT,
    item_images TEXT[],
    category_id INTEGER,
    item_status_id INTEGER DEFAULT 1,
    item_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    item_views_count INTEGER DEFAULT 0,
    item_likes_count INTEGER DEFAULT 0,
    deleted_at TIMESTAMP,

    CONSTRAINT fk_items_seller
        FOREIGN KEY (seller_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_items_category
        FOREIGN KEY (category_id)
        REFERENCES items_category_enum(category_id),

    CONSTRAINT fk_items_status
        FOREIGN KEY (item_status_id)
        REFERENCES status_enum(status_id)
);

CREATE INDEX idx_items_seller ON items(seller_id);
CREATE INDEX idx_items_category ON items(category_id);
CREATE INDEX idx_items_deleted_at ON items(deleted_at);
CREATE INDEX idx_items_created ON items(item_date DESC);

-- =========================================================
-- items_likes
-- =========================================================
CREATE TABLE items_likes (
    like_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    likes_item_id INTEGER,

    CONSTRAINT fk_items_likes_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_items_likes_item
        FOREIGN KEY (likes_item_id)
        REFERENCES items(item_id),

    CONSTRAINT uq_items_likes UNIQUE (user_id, likes_item_id)
);

CREATE INDEX idx_items_likes_user ON items_likes(user_id);
CREATE INDEX idx_items_likes_item ON items_likes(likes_item_id);

-- =========================================================
-- chat_rooms
-- =========================================================
CREATE TABLE chat_rooms (
    room_id SERIAL PRIMARY KEY,
    item_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_chat_rooms_item
        FOREIGN KEY (item_id)
        REFERENCES items(item_id)
);

CREATE INDEX idx_chat_rooms_item ON chat_rooms(item_id);

-- =========================================================
-- chat_messages
-- =========================================================
CREATE TABLE chat_messages (
    message_id SERIAL PRIMARY KEY,
    room_id INTEGER NOT NULL,
    sender_id INTEGER NOT NULL,
    "content" TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_chat_messages_room
        FOREIGN KEY (room_id)
        REFERENCES chat_rooms(room_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_messages_sender
        FOREIGN KEY (sender_id)
        REFERENCES users(user_id)
);

CREATE INDEX idx_chat_messages_room_created
ON chat_messages(room_id, created_at DESC);

-- =========================================================
-- chat_room_users
-- =========================================================
CREATE TABLE chat_room_users (
    room_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    last_read_message_id INTEGER,

    CONSTRAINT pk_chat_room_users PRIMARY KEY (room_id, user_id),

    CONSTRAINT fk_chat_room_users_room
        FOREIGN KEY (room_id)
        REFERENCES chat_rooms(room_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_room_users_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_chat_room_users_last_read
        FOREIGN KEY (last_read_message_id)
        REFERENCES chat_messages(message_id)
        ON DELETE SET NULL
);

CREATE INDEX idx_chat_room_users_room ON chat_room_users(room_id);
CREATE INDEX idx_chat_room_users_user ON chat_room_users(user_id);
